### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by giovannipizzi** [ekouts/pyfirecrest#6]
I have a very general question/suggestion - I realised that many kwargs of functions follow camelCase convention, rather than the more conventional approach of snake_case in python. E.g.
`simple_upload(self, machine, sourcePath, targetPath):`.

This makes the usage of the package a bit less convenient to python users. Do you think it would be possible to switch in a future release to e.g. `simple_upload(self, machine, source_path, target_path):` and similar?

**Comment by ekouts** [comment]
This is a very easy fix and I guess you have a point. I was getting the arguments directly from https://firecrest-api.cscs.ch/ . I will update before the next release.
